name: Node.js CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kanbananza-backend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - run: npm run test:unit

  acceptance-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kanbananza-backend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - run: npm run test:acceptance

  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kanbananza-backend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - run: npm run lint:check
      - run: npm run format:check
